stages:
  - deploy
  - finish

deploy:
  before_script:
    - 'yarn'
    - 'yarn before-ci'
    - 'yarn build'
  image: 'kkarczmarczyk/node-yarn'
  script: 'yarn deploy-only'
  stage: deploy

fail:
  image: 'kkarczmarczyk/node-yarn'
  script: 'yarn deploy-failed'
  stage: finish
  when: on_failure
