deploy:
  before_script:
    - 'yarn'
    - 'yarn before-ci'
  image: 'kkarczmarczyk/node-yarn'
  script: 'yarn deploy'
  stage: build

fail:
  image: 'kkarczmarczyk/node-yarn'
  script: 'yarn deploy-failed'
  stage: build
  when: on_failure
