before_script:
  - 'yarn before-ci'

build:
  image: 'kkarczmarczyk/node-yarn'
  script: 'yarn build'
  stage: 'build'

deploy:
  image: 'kkarczmarczyk/node-yarn'
  script: 'yarn deploy-only'
  stage: 'deploy'
