before_script:
  - 'yarn'
  - 'yarn before-ci'

deploy:
  image: 'kkarczmarczyk/node-yarn'
  script: 'yarn deploy'
  stage: deploy

fail:
  image: 'kkarczmarczyk/node-yarn'
  script: 'yarn deploy-failed'
  stage: deploy
  when: on_failure
